### ISSUE TITLE
TagCloud 报错

### ISSUE THREAD

**Issue by iChrAlpha** [volantis-x/hexo-theme-volantis#157]
## 描述

从 Material X 试图升级上来，但是即便是使用未作修改的 Volantis 主题，在 `hexo g` 时都会出现下述报错：

```
ERROR E:\_work\github\blog\themes\volantis\layout\tag.ejs:14
    12|               </div>
    13|               <div class="archive-item all-tags">
 >> 14|                 <% theme.widget.forEach(function(item){ %>
    15|                   <% if (item.class == 'tagcloud'){ %>
    16|                     <%- tagcloud(site.tags, {
    17|                         min_font: item.min_font,

theme.widget.forEach is not a function
TypeError: E:\_work\github\blog\themes\volantis\layout\tag.ejs:14
    12|               </div>
    13|               <div class="archive-item all-tags">
 >> 14|                 <% theme.widget.forEach(function(item){ %>
    15|                   <% if (item.class == 'tagcloud'){ %>
    16|                     <%- tagcloud(site.tags, {
    17|                         min_font: item.min_font,

theme.widget.forEach is not a function
    at eval (eval at compile (E:\_work\github\blog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:35:21)
    at returnedFn (E:\_work\github\blog\node_modules\ejs\lib\ejs.js:668:17)
    at viewFn._compiled (E:\_work\github\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (E:\_work\github\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at E:\_work\github\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (E:\_work\github\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\_work\github\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\_work\github\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:492:10)
    at resume_ (_stream_readable.js:977:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

## 环境
Hexo版本：4.2
`package.json`文件：
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.2.0",
    "hexo-blog-encrypt": "^3.0.12",
    "hexo-cli": "^3.1.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.2.0",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-lazyload-img-chrbeta": "0.0.3",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```

**Comment by xaoxuu** [comment]
是个BUG，我刚修复了你看看

最新一次提交的 `commit id`是 `6185fca3`

**Comment by iChrAlpha** [comment]
> 
> 
> 是个BUG，我刚修复了你看看
> 
> 最新一次提交的 `commit id`是 `6185fca3`

这个问题解决了，然后还有个建议：

行内代码在引用框内无法展示（图1），可能是配色一样导致，建议保留之前的方式（图2）

![行内代码-bug-1](https://user-images.githubusercontent.com/56496965/75649570-87b32f00-5c8e-11ea-829d-95c7e80b0a11.PNG)

![行内代码-bug-2](https://user-images.githubusercontent.com/56496965/75649574-8b46b600-5c8e-11ea-94d6-d2b007dc4d34.PNG)

**Comment by iChrAlpha** [comment]
不用了，我自己修改了配色导致的问题。作者的主题已经很完善了，谢谢！
