### ISSUE TITLE
文章内链接作文本的话无法生成静态文件

### ISSUE THREAD

**Issue by yinuxy** [volantis-x/hexo-theme-volantis#164]
大佬你好，我发现了一个BUG，就是我有一篇文章里面写的是JSP的配置，其中有一段话为
![image](https://user-images.githubusercontent.com/42272333/75984809-07a6f680-5f26-11ea-8aa4-d53a3a0545da.png)
当我执行`hexo s -d`生成的时候就会报错如下
```
TypeError [ERR_INVALID_URL]: Invalid URL: http://localhost:8080”
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at E:\HexoBlog\Hexo\node_modules\hexo-util\lib\is_external_link.js:21:18
    at Cache.apply (E:\HexoBlog\Hexo\node_modules\hexo-util\lib\cache.js:27:46)
    at isExternalLink (E:\HexoBlog\Hexo\node_modules\hexo-util\lib\is_external_link.js:19:16)
    at E:\HexoBlog\Hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:23:35
    at String.replace (<anonymous>)
    at Hexo.externalLinkFilter (E:\HexoBlog\Hexo\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\HexoBlog\Hexo\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\Hexo\node_modules\bluebird\js\release\async.js:15:14)
```
这似乎是一个BUG...希望大佬可以把规则写的活一点

**Comment by xaoxuu** [comment]
https://volantis.js.org/test/2020-03-06-test-url/

**Comment by xaoxuu** [comment]
我今天更换 markdwon 解析插件为 `hexo-renderer-marked` 时重现了这个错误，发现原因是此插件默认会自动识别 URL ，所以在 根目录配置文件中 `autolink: false` 即可。https://github.com/hexojs/hexo-renderer-marked
