### ISSUE TITLE
Cannot read property 'tagcloud' of null

### ISSUE THREAD

**Issue by tcp404** [volantis-x/hexo-theme-volantis#216]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [X] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [X] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 

> Cannot read property 'tagcloud' of null
tagcloud这块不知道为什么总是编译不过去
但是有生成html页面,
然而实际访问的时候依然访问不了.

```shell
E:\BLOG\GIT_BLOG>hexo g
INFO  Start processing
INFO  Files loaded in 599 ms
ERROR E:\BLOG\GIT_BLOG\themes\volantis\layout\tag.ejs:14
    12|               </div>
    13|               <div class="archive-item all-tags">
 >> 14|                 <% let tc = theme.widget.tagcloud; %>
    15|                 <%- tagcloud(site.tags, {
    16|                     min_font: tc.min_font,
    17|                     max_font: tc.max_font,

Cannot read property 'tagcloud' of null
TypeError: E:\BLOG\GIT_BLOG\themes\volantis\layout\tag.ejs:14
    12|               </div>
    13|               <div class="archive-item all-tags">
 >> 14|                 <% let tc = theme.widget.tagcloud; %>
    15|                 <%- tagcloud(site.tags, {
    16|                     min_font: tc.min_font,
    17|                     max_font: tc.max_font,

Cannot read property 'tagcloud' of null
    at eval (E:\BLOG\GIT_BLOG\themes\volantis\layout\tag.ejs:32:30)
    at tag (E:\BLOG\GIT_BLOG\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (E:\BLOG\GIT_BLOG\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (E:\BLOG\GIT_BLOG\node_modules\hexo\lib\theme\view.js:41:15)
    at E:\BLOG\GIT_BLOG\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (E:\BLOG\GIT_BLOG\node_modules\bluebird\js\release\util.js:16:23)
    at E:\BLOG\GIT_BLOG\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\BLOG\GIT_BLOG\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:478:10)
    at resume_ (_stream_readable.js:965:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
INFO  Generated: 2019/07/18/Git-基本操作说明/index.html
INFO  Generated: 2020/03/21/Electron-Note/index.html
INFO  Generated: 2019/07/14/SSM-配置文件/index.html
INFO  Generated: about/index.html
INFO  Generated: 2019/07/11/SSM-7-统一异常处理/index.html
INFO  Generated: 2019/07/13/SSM-8-Spring事务管理/index.html
INFO  Generated: 2019/07/10/SSM-6-上传和下载/index.html
INFO  Generated: 2019/07/07/SSM-4-数据绑定/index.html
INFO  Generated: 2019/06/09/C-Note/index.html
INFO  Generated: 2019/06/09/Java-About-Hash/index.html
INFO  Generated: 2019/06/09/Java-反射/index.html
INFO  Generated: 2019/05/19/Git命令大全/index.html
INFO  Generated: 2019/05/18/多端同步管理Hexo博客/index.html
INFO  Generated: 2019/05/15/几句话区分并行和并发/index.html
INFO  Generated: 2019/05/13/当小程序开发完成后/index.html
INFO  Generated: 2019/04/25/GoLang-Note-one/index.html
INFO  Generated: 2019/07/07/SSM-5-拦截器/index.html
INFO  Generated: 2019/04/25/Android【No-3】Intent/index.html
INFO  Generated: 2019/04/25/Android【No-2】点击事件监听/index.html
INFO  Generated: 2019/04/25/LeetCode-笔记【No-4】0x09-回文数/index.html
INFO  Generated: 2019/04/25/LeetCode-笔记【No-1】0x01-两数之和/index.html
INFO  Generated: 2019/04/25/通信中的加密与解密-详细版/index.html
INFO  Generated: 2019/04/25/通信中的加密与解密/index.html
INFO  Generated: 2019/01/01/Hello-World/index.html
INFO  Generated: archives/2019/index.html
INFO  Generated: archives/2019/04/index.html
INFO  Generated: 2019/04/25/LeetCode-笔记【No-3】0x0D-罗马数字转整数/index.html
INFO  Generated: archives/2019/page/2/index.html
INFO  Generated: archives/2019/05/index.html
INFO  Generated: archives/2019/01/index.html
INFO  Generated: archives/2019/06/index.html
INFO  Generated: archives/2019/07/index.html
INFO  Generated: archives/2020/index.html
INFO  Generated: categories/Android/index.html
INFO  Generated: categories/Git/index.html
INFO  Generated: archives/2020/03/index.html
INFO  Generated: categories/Electron/index.html
INFO  Generated: categories/GoLang/index.html
INFO  Generated: categories/Java/index.html
INFO  Generated: categories/LeetCode/index.html
INFO  Generated: categories/RSA/index.html
INFO  Generated: categories/SSM/index.html
INFO  Generated: categories/Other/index.html
INFO  Generated: index.html
INFO  Generated: categories/HEXO/index.html
INFO  Generated: page/2/index.html
INFO  Generated: categories/Note/index.html
INFO  Generated: page/3/index.html
INFO  Generated: tags/Android/index.html
INFO  Generated: tags/git/index.html
INFO  Generated: tags/Electron/index.html
INFO  Generated: tags/Java/index.html
INFO  Generated: tags/C-Language/index.html
INFO  Generated: tags/GoLang/index.html
INFO  Generated: tags/LeetCode/index.html
INFO  Generated: tags/并行与并发/index.html
INFO  Generated: tags/SSM/index.html
INFO  Generated: tags/note/index.html
INFO  Generated: 2019/04/25/LeetCode-笔记【No-2】0x07-整数反转/index.html
INFO  Generated: 2019/04/25/RSA加密原理/index.html
INFO  Generated: tags/RSA/index.html
INFO  Generated: tags/HEXO/index.html
INFO  Generated: tags/算法/index.html
INFO  63 files generated in 1.78 s
```
## Environment Information
Win10

### Node.js and NPM Information

```
node: v12.16.1
npm: 6.13.4
hexo: 4.2.0
```

### Package dependencies Information

```
hexo-site@0.0.0 E:\BLOG\GIT_BLOG
+-- hexo@4.2.0
+-- hexo-asset-image@0.0.5 
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.1.6
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-git-backup@0.1.3
+-- hexo-helper-qrcode@1.0.2
+-- hexo-lazyload-image@1.0.6
+-- hexo-related-popular-posts@4.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-tag-aplayer@3.0.4
`-- hexo-wordcount@6.0.1
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TCP404
subtitle: ''
description: ''
keywords:
author: Mr.Pro
language: zh-CN
timezone: 'Asia/Shanghai'           # 时区
favicon: /images/icon/favicon.png   # 图标
use_cdn: ture

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.tcp404.com 
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # 新帖子的文件名
default_layout: post
titlecase: false         # 将标题转换为标题title case
external_link:           # 在新选项卡中打开外部链接
  enable: true             # true: 开启   false：关闭
  field: site              # 适用范围
  exclude: ''            # 不适用范围
filename_case: 0         # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false     # 显示草稿
post_asset_folder: false # 启动 Asset 文件夹 启用后新建文章时回生成同名文件夹 >_ : npm install https://github.com/CodeFalling/hexo-asset-image --save
relative_link: false     # 把链接改为与根目录的相对位址
future: true             # 显示未来的文章
highlight:               # 代码块设置
  enable: true             # true: 开启   false：关闭 
  line_number: true        # 行号
  auto_detect: false       # 如果未指定语言，则启用自动检测
  tab_replace: ''          # 用 n 个空格替换 tabs；如果值为空，则不会替换 tabs
  wrap: true               # 将代码块包装在框中
  hljs: false              # 对CSS类使用hljs-* 前缀

# 主页设置
# path：博客索引页的根路径。（默认值 = ''）
# per_page：每页发布问题。（0 关闭分页功能）
# order_by：发布排序。（默认按日期排序）
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类 & 标签
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间 格式化
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## 使用post的日期作为更新日期，除非设置了front-matter
use_date_for_updated: false

# 分页
per_page: 20          # 设置为0可以禁用分页
pagination_dir: page  # 分页目录
# 包括或不包括目录和文件
#在 Hexo 配置文件中，通过设置 include/exclude 可以让 Hexo 进行处理或忽略某些目录和文件夹。你可以使用 glob 表达式 对目录和文件进行匹配。
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/deployment.html

# >_ :  npm install hexo-deployer-git --save
deploy:
  type: git
  repo: https://github.com/TCP404/tcp404.github.io.git
  branch: master
# >_ :  npm install hexo-git-backup --save
backup:
  type: git
  theme: volantis
  message: Back up www.tcp404.com blog
  repository:
    github: https://github.com/TCP404/tcp404.github.io.git,backup
```

### Volantis Configuration

blog\source\_data\widget.yml
```yml
# ---------------------------------------
# 博主信息
blogger:
  class: blogger
  display: [desktop] # [desktop, mobile]
  avatar: /img/logo.svg
  title:
  subtitle:
  jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
  social: true
# ---------------------------------------
# 标签云 widget
tagcloud:
  class: tagcloud
  display: [desktop] # [desktop, mobile]
  header:
    icon: fas fa-tags
    title: 热门标签
    url: /blog/tags/
  min_font: 14
  max_font: 24
  color: true
  start_color: '#999'
  end_color: '#555'
# ---------------------------------------
# 文章目录 widget (valid only in articles)
toc:
  class: toc
  display: [desktop, mobile] # [desktop, mobile]
  header:
    icon: fas fa-list
    title: 本文目录
  list_number: false
  min_depth: 2
  max_depth: 5
# ---------------------------------------
# 分类 widget
category:
  class: category
  display: [desktop] # [desktop, mobile]
  header:
    icon: fas fa-folder-open
    title: 文章分类
    url: /blog/categories/
# ---------------------------------------
# 相关文章 widget
# >_ : npm i -S hexo-related-popular-posts
related_posts:
  class: related_posts 
  display: [desktop, mobile] # [desktop, mobile]
  header:
    icon: fas fa-bookmark
    title: 相关文章
  max_count: 5
# ---------------------------------------
# 版权 widget (valid only in articles)
copyright:
  class: copyright
  display: [desktop, mobile] # [desktop, mobile]
  blockquote: true
  permalink: '本文永久链接是：'
  content:
    - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
    - permalink
# ---------------------------------------
# 二维码 widget
donate:
  class: qrcode
  display: [desktop, mobile] # [desktop, mobile]
  height: 64px  # 默认高度
  fancybox: true
  images:
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
    - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
# You can add your own widget here or 'blog/source/_data/widget.yml'
# class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/
```
themes\volantis\_config.yml
```yml
cover:
  scheme: docs # docs, blog
  display:
    home: true
    archive: true
    others: true # can be written in front-matter 'cover: true'
  title: TCP404
  logo: https://cdn.jsdelivr.net/gh/TCP404/HEXO-CDN/images/icon/favicon.png
  subtitle: 'Show me the code!'
  search: 'Search...' # 封面搜索栏提示文字
  features:
    - name: 博文
      icon: fas fa-rss
      url: /
    - name: 项目
      icon: fas fa-code-branch
      url: https://github.com/Mr-O4/GoTE-miniprogram
      rel: external nofollow noopener noreferrer
      target: _blank
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 归档
      icon: fas fa-book
      url: archives/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 关于
      icon: fas fa-info-circle
      url: about/


# Navigation Bar
navbar:
   ...
```

**Comment by xaoxuu** [comment]
这个报错指的是 theme.widget 为 null，也就是说 theme.widget 格式错误无法读取。

**Comment by xaoxuu** [comment]
主题文件中原有的 widget 请不要移动，自己新增的可以写在数据文件中。

**Comment by tcp404** [comment]
> 主题文件中原有的 widget 请不要移动，自己新增的可以写在数据文件中。

把widget.yml的内容移回主题文件后已恢复正常.
感谢!
