### ISSUE TITLE
实现 npm i hexo-theme-volantis 安装主题

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#428]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

实现 `npm i hexo-theme-volantis` 安装主题

**Comment by MHuiG** [comment]
https://hexo.io/zh-cn/docs/themes

**Comment by MHuiG** [comment]
这是不可能实现的

**Comment by MHuiG** [comment]
快去给Hexo提issues  🤣🤣🤣

**Comment by xaoxuu** [comment]
可以啊，你试试 `npm i hexo-theme-landscape` 和 `npm i hexo-theme-next`

**Comment by MHuiG** [comment]
你测试成功了？

**Comment by xaoxuu** [comment]
![image](https://user-images.githubusercontent.com/16400144/89706727-e649ab00-d99a-11ea-97fa-c2b1fb757062.png)

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/89706749-18f3a380-d99b-11ea-99ff-a7104ae6af18.png)

**Comment by xaoxuu** [comment]
创建一个全新的博客，然后 
```
npm i
npm i hexo-theme-next
```
然后改 `_config.yml`
```
theme: next
```
然后运行，一次就成功了。

**Comment by MHuiG** [comment]
我这边有依赖和主题冲突了

**Comment by xaoxuu** [comment]
我想做成 Actions ，发布 release 的时候自动发布到 npm

**Comment by MHuiG** [comment]
https://github.com/MiniValine/MiniValine/blob/master/.github/workflows/npm-publish.yml

**Comment by MHuiG** [comment]
但是这样就不能够修改主题文件了

**Comment by xaoxuu** [comment]
可以在这个库里面测试 https://github.com/volantis-x/testnpm

**Comment by xaoxuu** [comment]
就是多一种选择而已

**Comment by xaoxuu** [comment]
用是可以用了，但是 `hexo clean` 的时候终端报错：
```bash
> hexo clean
ERROR {
  err: /Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/hexo-theme-volantis/package.json:2
    "_from": "hexo-theme-volantis",
           ^
  
  SyntaxError: Unexpected token ':'
      at new Script (vm.js:88:7)
      at createScript (vm.js:263:10)
      at runInThisContext (vm.js:311:10)
      at /Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/hexo/lib/hexo/index.js:313:18
      at tryCatcher (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/xaoxuu/Downloads/testnpm/sss/blog/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
} Plugin load failed: %s hexo-theme-volantis
INFO  Deleted database.

> hexo server
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
```

> 通过 `npm i hexo-theme-landscape` 使用官方主题时没有报错。

**Comment by MHuiG** [comment]
https://github.com/hexojs/hexo/issues/4449

升级Hexo至5.0.2以上即可

**Comment by Reqwey** [comment]
> 但是这样就不能够修改主题文件了

主题的`_config.yml`能改吗

**Comment by xaoxuu** [comment]
https://hexo.io/zh-cn/docs/configuration#使用代替主题配置文件
