### ISSUE TITLE
需求首页轮播图片功能，以顶替文章置顶功能

### ISSUE THREAD

**Issue by Tikas** [volantis-x/hexo-theme-volantis#499]
## 需求描述
查看过 heson 大大的轮播图片文章之后，很想去添加到现有的  4.0.0-rc.4 版本里。

然而，考虑到移动端手机用户访问时，布局会改变，对只能看懂代码却没有写代码能力的我来说，要去实现相关修改和增加功能，实在太难了！

/捂脸

再次向大大发起需求建议：

1.同侧边小部件一样，增加 desktop, mobile 显示模式
2.当 mobile 用户访问显示时，布局可以设置为：上方为轮播，下方为两个固定图排在同一行，并且可以为下方两个固定图设置是否显示

由于主题已经引用了 JQuery 库，增加这轮播功能一定会给 Volantis 带来更多精彩！

这样可以有另一种方案来达到置顶的效果。

## 参考链接
[给Hexo Volantis主题添加图片轮播功能](https://www.heson10.com/posts/19736.html)

**Comment by heson525** [comment]
我那段css代码已经做了手机的自适应，可以尝试自己修改。当然，如果 @xaoxuu 在百忙之中抽出时间适配的话，那无疑是新手福音。😉

**Comment by Tikas** [comment]
好的，感谢大大，明天来试试看

**Comment by Tikas** [comment]
今天动手去尝试，完全按文章方法去增加，然而没有效果，不会显示轮播，不知道什么原因，4.0.0.rc.4版本

**Comment by heson525** [comment]
浏览器F12看下报错的信息。

**Comment by Tikas** [comment]
main_banner.js:6 Uncaught ReferenceError: banner_max is not defined
    at loads (main_banner.js:6)
    at main_banner.js:104

jquery.min.js:2 jQuery.Deferred exception: banner_max is not defined ReferenceError: banner_max is not defined
    at banner_number (http://localhost:4000/js/main_banner.js:82:23)
    at HTMLDocument.<anonymous> (http://localhost:4000/js/main_banner.js:24:2)
    at e (https://cdn.jsdelivr.net/npm/jquery@3.5/dist/jquery.min.js:2:30005)
    at t (https://cdn.jsdelivr.net/npm/jquery@3.5/dist/jquery.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js:2

jquery.min.js:2 Uncaught ReferenceError: banner_max is not defined
    at banner_number (main_banner.js:82)
    at HTMLDocument.<anonymous> (main_banner.js:24)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)

**Comment by Tikas** [comment]
我把 main_banner.js 所有空行都去掉了，所以：

第 6 行：var img_num = banner_max

第 104 行：loads();

**Comment by Tikas** [comment]
会不会是新版本，主题配置更改导致的，我试试看 var img_num = 3

就不会提示 main_banner.js:6 Uncaught ReferenceError: banner_max is not defined 错误了

但是，会报新的错误：
黄色警报：jquery.min.js:2 jQuery.Deferred exception: speed is not defined ReferenceError: speed is not defined
    at HTMLDocument.<anonymous> (http://localhost:4000/js/main_banner.js:25:43)

红色错误：jquery.min.js:2 Uncaught ReferenceError: speed is not defined
    at HTMLDocument.<anonymous> (main_banner.js:25)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)

第 25 行的代码是：timer = setInterval(auto_replace_banner, speed * 1000);//banner切换计时器

**Comment by Tikas** [comment]
要辛苦大大去跟进问题了，我先把这所有的增加的代码清空还原到 4.0.0-rc.4 

等待大大抽空改进后，再来尝试此轮播功能

**Comment by Tikas** [comment]
今天看到提问的智慧，再结合自身情况，发现提出问题后很多地方呆呆的
/捂脸
虽说新人不懂的太多，也尝试去获取这些基础知识，时间各种关系，未来成长线还是很长。
但是，现在回顾一下这次的提问之后的所做行为，太萌了！
也许增加轮播，会带来顶替置顶的效果。从开发角度来说，还要处理原本的主题布局风格，这是个大改。
深层处会带来代码性能等问题。
我决定关闭这个提问，F12只是一个开始。
