### ISSUE TITLE
部署到Git时报错

### ISSUE THREAD

**Issue by AnotiaWang** [volantis-x/hexo-theme-volantis#542]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述
在使用`hexo deploy`部署到 Git 仓库时报错

## 环境信息 

Windows Server 2012 R2

### Detail
```
FATAL {
  err: TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
      at copyFile (fs.js:1972:10)
      at tryCatcher (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at ret (eval at makeNodePromisifiedEval (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
      at C:\Users\Administrator\Desktop\Blog\node_modules\hexo-fs\lib\fs.js:144:39
      at tryCatcher (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (C:\Users\Administrator\Desktop\Blog\node_modules\bluebird\js\release\promise.js:673:18) {
    code: 'ERR_INVALID_ARG_TYPE'
  }
}
```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```
$ node -v && npm -v
v14.15.1
6.14.8
```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
+-- core-js@3.8.1
+-- hexo@5.2.0
+-- hexo-algoliasearch@0.4.2
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-indexed@1.2.1
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.1
+-- hexo-generator-searchdb@1.3.3
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-html-minifier@1.0.0
+-- hexo-lazyload-image@1.0.9
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-pug@1.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-theme-volantis@4.2.0
+-- hexo-uglify@1.1.0
+-- hexo-wordcount@6.0.1
+-- minimatch@3.0.4
`-- npm@6.14.9

```

</details>

**Comment by dearxujiee** [comment]
git仓库是什么，github?or codding?

**Comment by AnotiaWang** [comment]
> git仓库是什么，github?or codding?

都报错

**Comment by dearxujiee** [comment]
本地报错吗

**Comment by AnotiaWang** [comment]
> 本地报错吗
> 

本地 hexo s 没有报错，只有 hexo d 的时候报错

**Comment by dearxujiee** [comment]
> > 本地报错吗
> 
> 本地 hexo s 没有报错，只有 hexo d 的时候报错

你这个可能是node版本太高导致的，你把node卸载后再装10.15.1版本的试试

**Comment by inkss** [comment]
https://github.com/hexojs/hexo/issues/4275

> Please temporarily use Node.js v13 instead of v14
>
> Update: Hexo v5.0.0 released.
