### ISSUE TITLE
执行hexo s后报错

### ISSUE THREAD

**Issue by Pems002** [volantis-x/hexo-theme-volantis#599]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

hexo s后一直报错以下，ERROR是浏览器访问时开始的

```bash
E:\Git\Blog>hexo s
INFO  Validating config
Inferno is in development mode.
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR {
  err: TypeError: E:\Git\Blog\themes\volantis\layout\layout.ejs:3
      1| <!DOCTYPE html>
      2| <html lang="<%- config.language %>">
   >> 3|   <%- partial('_partial/head') %>
      4|   <body>
      5|     <%- partial('_partial/header', null, {cache: false, path: path}) %>
      6|     <div id="l_body">

  E:\Git\Blog\themes\volantis\layout\_partial\head.ejs:91
      89|   <!-- feed -->
      90|   <% if (config.feed && config.feed.path){ %>
   >> 91|     <%- feed_tag(config.feed.path, {title: config.title}) %>
      92|   <% } %>
      93|
      94|   <!-- import meta -->

  path must be a string!
      at Object.feedTagHelper (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\feed_tag.js:15:41)
      at eval (E:\Git\Blog\themes\volantis\layout\_partial\head.ejs:153:17)
      at head (E:\Git\Blog\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiledSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval (E:\Git\Blog\themes\volantis\layout\layout.ejs:15:17)
      at layout (E:\Git\Blog\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\Git\Blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\Git\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\Git\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\Git\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\Git\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\Git\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    path: 'E:\\Git\\Blog\\themes\\volantis\\layout\\layout.ejs'
  }
} Render HTML failed: index.html
Unhandled rejection TypeError: E:\Git\Blog\themes\volantis\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%- config.language %>">
 >> 3|   <%- partial('_partial/head') %>
    4|   <body>
    5|     <%- partial('_partial/header', null, {cache: false, path: path}) %>
    6|     <div id="l_body">

E:\Git\Blog\themes\volantis\layout\_partial\head.ejs:91
    89|   <!-- feed -->
    90|   <% if (config.feed && config.feed.path){ %>
 >> 91|     <%- feed_tag(config.feed.path, {title: config.title}) %>
    92|   <% } %>
    93|
    94|   <!-- import meta -->

path must be a string!
    at Object.feedTagHelper (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\feed_tag.js:15:41)
    at eval (E:\Git\Blog\themes\volantis\layout\_partial\head.ejs:153:17)
    at head (E:\Git\Blog\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Git\Blog\themes\volantis\layout\layout.ejs:15:17)
    at layout (E:\Git\Blog\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Git\Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\Git\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Git\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Git\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Git\Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Git\Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Git\Blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

### 主题版本

您当前使用的版本为：4.3.1

### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [x] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 https://github.com/Pems002/Blog

### 截图

<details><summary>相关截图</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
atom 和  rss2 先只保留一个

https://github.com/Pems002/Blog/blob/8e09846162dc86a6025a7a758fbfce6bd81146bb/_config.yml#L74-L75

<blockquote><img src="https://avatars.githubusercontent.com/u/29890309?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Pems002/Blog">Pems002/Blog</a></strong></div><div>A personal blog with Hexo deploy on Github Pages. Contribute to Pems002/Blog development by creating an account on GitHub.</div></blockquote>

**Comment by Pems002** [comment]
刚看到回复设置了就没问题了，谢谢
