### ISSUE TITLE
安装并启用hexo-related-popular-posts后，所有博文都无法打开

### ISSUE THREAD

**Issue by Giresharu** [volantis-x/hexo-theme-volantis#650]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

安装并启用hexo-related-popular-posts后，所有博文都无法打开。
卸载并关闭后恢复正常。
直接下载和使用淘宝镜像下载都尝试过

### 主题版本

您当前使用的版本为：4.3.1

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml

 body:

      # ----------------
      # 相关文章，需要安装插件 (for layout: post)
      # npm i hexo-related-popular-posts
      related_posts:
        enable: true
        title: 相关文章
        icon: fas fa-bookmark
        max_count: 5
        # 设为空则不使用文章头图
        placeholder_img: 
      # ----------------

```
powershell报错：
```
07:53:35.069 DEBUG Rendering HTML post: 2013/12/25/no-title/index.html
Unhandled rejection TypeError: E:\Project\Blog\rebuildblog\demo\node_modules\hexo-theme-volantis\layout\post.ejs:3
    1| <%- partial('_pre') %>
    2| <div class='l_main<%- page.sidebar == false ? ' no_sidebar' : '' %>'>
 >> 3|   <%- partial('_partial/article', {post: page, index: false}) %>
    4| </div>
    5| <%- partial('_partial/side') %>
    6|

E:\Project\Blog\rebuildblog\demo\node_modules\hexo-theme-volantis\layout\_partial\article.ejs:42
    40|       <% } %>
    41|       <% if (['post'].includes(page.layout) && footer_widget.related_posts && footer_widget.related_posts.enable == true) { %>
 >> 42|         <%-
    43|         htmlGenerator(
    44|           popular_posts_json({ maxCount: footer_widget.related_posts.max_count , ulClass: 'vlts-rps' , PPMixingRate: 0.2 , isImage: true , isExcerpt: true} , post )
    45|         )

Cannot read property 'length' of null
    at generateHTML (E:\Project\Blog\rebuildblog\demo\node_modules\hexo-theme-volantis\scripts\related_posts\index.js:27:29)
    at Object.<anonymous> (E:\Project\Blog\rebuildblog\demo\node_modules\hexo-theme-volantis\scripts\related_posts\index.js:46:19)
    at eval (E:\Project\Blog\rebuildblog\demo\node_modules\hexo-theme-volantis\layout\_partial\article.ejs:88:9)
    at article (E:\Project\Blog\rebuildblog\demo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Project\Blog\rebuildblog\demo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Project\Blog\rebuildblog\demo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Project\Blog\rebuildblog\demo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Project\Blog\rebuildblog\demo\node_modules\hexo-theme-volantis\layout\post.ejs:16:17)
    at post (E:\Project\Blog\rebuildblog\demo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Project\Blog\rebuildblog\demo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Project\Blog\rebuildblog\demo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Project\Blog\rebuildblog\demo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Project\Blog\rebuildblog\demo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Project\Blog\rebuildblog\demo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Project\Blog\rebuildblog\demo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by Colsrch** [comment]
`npm i hexo-related-popular-posts --save`  ?
hexo cl 一下？

**Comment by xaoxuu** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/a8674fd3d185e2599e3697008f8b52f39a579940/scripts/helpers/related_posts/index.js#L27

这里改成这样试试：
```
if (cfg.placeholder_img && cfg.placeholder_img.length > 0) {
```

**Comment by erro-life** [comment]
我碰到这个问题了

placeholder_img: 设为空导致文章不显示

**Comment by MHuiG** [comment]
dev 分支已经改好了

https://github.com/volantis-x/hexo-theme-volantis/blob/b1759aafe7bf00d82e11430aed8fe74b77e56503/scripts/helpers/related_posts/index.js#L27
